package pl.com.mobilelabs.mobilus.services.managementservice;

enum ManagementServiceState {
  CONFIGURATION_CHANGED_CURRENT_STATE_REQUEST_SENT, CONFIGURATION_CHANGED_DEVICES_LIST_REQUEST_SENT, CONFIGURATION_CHANGED_DEVICE_GROUPS_REQUEST_SENT, CONFIGURATION_CHANGED_DEVICE_PLACES_REQUEST_SENT, CONFIGURATION_CHANGED_LOGIN_REQUEST_SENT, CONFIGURATION_CHANGED_SCENES_REQUEST_SENT, CONNECTED_LOGGED_IDLE, CONNECTED_NOT_LOGGED_IDLE, CONNECTING, CURRENT_STATE_REQUEST_SENT, DEVICES_LIST_REQUEST_SENT, DEVICE_GROUPS_REQUEST_SENT, DEVICE_PLACES_REQUEST_SENT, DEVICE_SETTINGS_REQUEST_SENT, DISCONNECTED_IDLE, LOGIN_REQUEST_SENT, SCENES_REQUEST_SENT, SESSION_EXPIRED_LOGIN_REQUEST_SENT;
  
  static {
    CONNECTING = new ManagementServiceState("CONNECTING", 1);
    CONNECTED_NOT_LOGGED_IDLE = new ManagementServiceState("CONNECTED_NOT_LOGGED_IDLE", 2);
    LOGIN_REQUEST_SENT = new ManagementServiceState("LOGIN_REQUEST_SENT", 3);
    DEVICE_SETTINGS_REQUEST_SENT = new ManagementServiceState("DEVICE_SETTINGS_REQUEST_SENT", 4);
    DEVICES_LIST_REQUEST_SENT = new ManagementServiceState("DEVICES_LIST_REQUEST_SENT", 5);
    CURRENT_STATE_REQUEST_SENT = new ManagementServiceState("CURRENT_STATE_REQUEST_SENT", 6);
    DEVICE_PLACES_REQUEST_SENT = new ManagementServiceState("DEVICE_PLACES_REQUEST_SENT", 7);
    DEVICE_GROUPS_REQUEST_SENT = new ManagementServiceState("DEVICE_GROUPS_REQUEST_SENT", 8);
    SCENES_REQUEST_SENT = new ManagementServiceState("SCENES_REQUEST_SENT", 9);
    CONNECTED_LOGGED_IDLE = new ManagementServiceState("CONNECTED_LOGGED_IDLE", 10);
    CONFIGURATION_CHANGED_LOGIN_REQUEST_SENT = new ManagementServiceState("CONFIGURATION_CHANGED_LOGIN_REQUEST_SENT", 11);
    CONFIGURATION_CHANGED_DEVICES_LIST_REQUEST_SENT = new ManagementServiceState("CONFIGURATION_CHANGED_DEVICES_LIST_REQUEST_SENT", 12);
    CONFIGURATION_CHANGED_CURRENT_STATE_REQUEST_SENT = new ManagementServiceState("CONFIGURATION_CHANGED_CURRENT_STATE_REQUEST_SENT", 13);
    CONFIGURATION_CHANGED_DEVICE_PLACES_REQUEST_SENT = new ManagementServiceState("CONFIGURATION_CHANGED_DEVICE_PLACES_REQUEST_SENT", 14);
    CONFIGURATION_CHANGED_DEVICE_GROUPS_REQUEST_SENT = new ManagementServiceState("CONFIGURATION_CHANGED_DEVICE_GROUPS_REQUEST_SENT", 15);
    CONFIGURATION_CHANGED_SCENES_REQUEST_SENT = new ManagementServiceState("CONFIGURATION_CHANGED_SCENES_REQUEST_SENT", 16);
    SESSION_EXPIRED_LOGIN_REQUEST_SENT = new ManagementServiceState("SESSION_EXPIRED_LOGIN_REQUEST_SENT", 17);
    $VALUES = new ManagementServiceState[] { 
        DISCONNECTED_IDLE, CONNECTING, CONNECTED_NOT_LOGGED_IDLE, LOGIN_REQUEST_SENT, DEVICE_SETTINGS_REQUEST_SENT, DEVICES_LIST_REQUEST_SENT, CURRENT_STATE_REQUEST_SENT, DEVICE_PLACES_REQUEST_SENT, DEVICE_GROUPS_REQUEST_SENT, SCENES_REQUEST_SENT, 
        CONNECTED_LOGGED_IDLE, CONFIGURATION_CHANGED_LOGIN_REQUEST_SENT, CONFIGURATION_CHANGED_DEVICES_LIST_REQUEST_SENT, CONFIGURATION_CHANGED_CURRENT_STATE_REQUEST_SENT, CONFIGURATION_CHANGED_DEVICE_PLACES_REQUEST_SENT, CONFIGURATION_CHANGED_DEVICE_GROUPS_REQUEST_SENT, CONFIGURATION_CHANGED_SCENES_REQUEST_SENT, SESSION_EXPIRED_LOGIN_REQUEST_SENT };
  }
  
  public boolean isConnected() {
    return !(this == DISCONNECTED_IDLE || this == CONNECTING);
  }
  
  public boolean isLogged() {
    return !(this == DISCONNECTED_IDLE || this == CONNECTING || this == CONNECTED_NOT_LOGGED_IDLE);
  }
  
  public boolean shouldDownloadData() {
    return !(this == DISCONNECTED_IDLE || this == CONNECTING || this == CONNECTED_NOT_LOGGED_IDLE || this == CONNECTED_LOGGED_IDLE);
  }
}


/* Location:              C:\Users\rafal\Downloads\Mobius_jar.jar!\pl\com\mobilelabs\mobilus\services\managementservice\ManagementServiceState.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */