package pl.com.mobilelabs.mobilus.model.communication;

public enum MessageType {
  CALL_EVENTS,
  CURRENT_STATE_REQUEST,
  CURRENT_STATE_RESPONSE,
  DEVICES_LIST_REQUEST,
  DEVICES_LIST_RESPONSE,
  DEVICE_GROUPS_REQUEST,
  DEVICE_GROUPS_RESPONSE,
  DEVICE_PLACES_REQUEST,
  DEVICE_PLACES_RESPONSE,
  DEVICE_SETTINGS_REQUEST,
  DEVICE_SETTINGS_RESPONSE,
  FIRMWARE_UPDATE_REQUEST,
  FIRMWARE_UPDATE_RESPONSE,
  HISTORICAL_EVENTS_REQUEST,
  HISTORICAL_EVENTS_RESPONSE,
  LOGIN_REQUEST,
  LOGIN_RESPONSE,
  NETWORK_SETTINGS_REQUEST,
  NETWORK_SETTINGS_RESPONSE,
  PROGRAM_NEW_DEVICE_REQUEST,
  PROGRAM_NEW_DEVICE_RESPONSE,
  SCENES_REQUEST,
  SCENES_RESPONSE,
  UNKNOWN(0),
  UPDATE_DEVICE_GROUP_REQUEST(0),
  UPDATE_DEVICE_GROUP_RESPONSE(0),
  UPDATE_DEVICE_PLACE_REQUEST(0),
  UPDATE_DEVICE_PLACE_RESPONSE(0),
  UPDATE_DEVICE_REQUEST(0),
  UPDATE_DEVICE_RESPONSE(0),
  UPDATE_SCENE_REQUEST(0),
  UPDATE_SCENE_RESPONSE(0),
  UPDATE_USER_REQUEST(0),
  UPDATE_USER_RESPONSE(0),
  USER_LIST_REQUEST(0),
  USER_LIST_RESPONSE(0),
  WIFI_NETWORK_LIST_REQUEST(0),
  WIFI_NETWORK_LIST_RESPONSE(0);
  
  private int value;
  
  static {
    LOGIN_REQUEST = new MessageType("LOGIN_REQUEST", 1, 1);
    LOGIN_RESPONSE = new MessageType("LOGIN_RESPONSE", 2, 2);
    DEVICES_LIST_REQUEST = new MessageType("DEVICES_LIST_REQUEST", 3, 3);
    DEVICES_LIST_RESPONSE = new MessageType("DEVICES_LIST_RESPONSE", 4, 4);
    DEVICE_PLACES_REQUEST = new MessageType("DEVICE_PLACES_REQUEST", 5, 5);
    DEVICE_PLACES_RESPONSE = new MessageType("DEVICE_PLACES_RESPONSE", 6, 6);
    DEVICE_GROUPS_REQUEST = new MessageType("DEVICE_GROUPS_REQUEST", 7, 7);
    DEVICE_GROUPS_RESPONSE = new MessageType("DEVICE_GROUPS_RESPONSE", 8, 8);
    SCENES_REQUEST = new MessageType("SCENES_REQUEST", 9, 9);
    SCENES_RESPONSE = new MessageType("SCENES_RESPONSE", 10, 10);
    HISTORICAL_EVENTS_REQUEST = new MessageType("HISTORICAL_EVENTS_REQUEST", 11, 11);
    HISTORICAL_EVENTS_RESPONSE = new MessageType("HISTORICAL_EVENTS_RESPONSE", 12, 12);
    CALL_EVENTS = new MessageType("CALL_EVENTS", 13, 13);
    UPDATE_USER_REQUEST = new MessageType("UPDATE_USER_REQUEST", 14, 14);
    UPDATE_USER_RESPONSE = new MessageType("UPDATE_USER_RESPONSE", 15, 15);
    UPDATE_SCENE_REQUEST = new MessageType("UPDATE_SCENE_REQUEST", 16, 16);
    UPDATE_SCENE_RESPONSE = new MessageType("UPDATE_SCENE_RESPONSE", 17, 17);
    UPDATE_DEVICE_PLACE_REQUEST = new MessageType("UPDATE_DEVICE_PLACE_REQUEST", 18, 18);
    UPDATE_DEVICE_PLACE_RESPONSE = new MessageType("UPDATE_DEVICE_PLACE_RESPONSE", 19, 19);
    UPDATE_DEVICE_GROUP_REQUEST = new MessageType("UPDATE_DEVICE_GROUP_REQUEST", 20, 20);
    UPDATE_DEVICE_GROUP_RESPONSE = new MessageType("UPDATE_DEVICE_GROUP_RESPONSE", 21, 21);
    PROGRAM_NEW_DEVICE_REQUEST = new MessageType("PROGRAM_NEW_DEVICE_REQUEST", 22, 22);
    PROGRAM_NEW_DEVICE_RESPONSE = new MessageType("PROGRAM_NEW_DEVICE_RESPONSE", 23, 23);
    UPDATE_DEVICE_REQUEST = new MessageType("UPDATE_DEVICE_REQUEST", 24, 24);
    UPDATE_DEVICE_RESPONSE = new MessageType("UPDATE_DEVICE_RESPONSE", 25, 25);
    CURRENT_STATE_REQUEST = new MessageType("CURRENT_STATE_REQUEST", 26, 26);
    CURRENT_STATE_RESPONSE = new MessageType("CURRENT_STATE_RESPONSE", 27, 27);
    DEVICE_SETTINGS_REQUEST = new MessageType("DEVICE_SETTINGS_REQUEST", 28, 28);
    DEVICE_SETTINGS_RESPONSE = new MessageType("DEVICE_SETTINGS_RESPONSE", 29, 29);
    NETWORK_SETTINGS_REQUEST = new MessageType("NETWORK_SETTINGS_REQUEST", 30, 30);
    NETWORK_SETTINGS_RESPONSE = new MessageType("NETWORK_SETTINGS_RESPONSE", 31, 31);
    WIFI_NETWORK_LIST_REQUEST = new MessageType("WIFI_NETWORK_LIST_REQUEST", 32, 32);
    WIFI_NETWORK_LIST_RESPONSE = new MessageType("WIFI_NETWORK_LIST_RESPONSE", 33, 33);
    USER_LIST_REQUEST = new MessageType("USER_LIST_REQUEST", 34, 34);
    USER_LIST_RESPONSE = new MessageType("USER_LIST_RESPONSE", 35, 35);
    FIRMWARE_UPDATE_REQUEST = new MessageType("FIRMWARE_UPDATE_REQUEST", 36, 36);
    FIRMWARE_UPDATE_RESPONSE = new MessageType("FIRMWARE_UPDATE_RESPONSE", 37, 37);
    $VALUES = new MessageType[] { 
        UNKNOWN, LOGIN_REQUEST, LOGIN_RESPONSE, DEVICES_LIST_REQUEST, DEVICES_LIST_RESPONSE, DEVICE_PLACES_REQUEST, DEVICE_PLACES_RESPONSE, DEVICE_GROUPS_REQUEST, DEVICE_GROUPS_RESPONSE, SCENES_REQUEST, 
        SCENES_RESPONSE, HISTORICAL_EVENTS_REQUEST, HISTORICAL_EVENTS_RESPONSE, CALL_EVENTS, UPDATE_USER_REQUEST, UPDATE_USER_RESPONSE, UPDATE_SCENE_REQUEST, UPDATE_SCENE_RESPONSE, UPDATE_DEVICE_PLACE_REQUEST, UPDATE_DEVICE_PLACE_RESPONSE, 
        UPDATE_DEVICE_GROUP_REQUEST, UPDATE_DEVICE_GROUP_RESPONSE, PROGRAM_NEW_DEVICE_REQUEST, PROGRAM_NEW_DEVICE_RESPONSE, UPDATE_DEVICE_REQUEST, UPDATE_DEVICE_RESPONSE, CURRENT_STATE_REQUEST, CURRENT_STATE_RESPONSE, DEVICE_SETTINGS_REQUEST, DEVICE_SETTINGS_RESPONSE, 
        NETWORK_SETTINGS_REQUEST, NETWORK_SETTINGS_RESPONSE, WIFI_NETWORK_LIST_REQUEST, WIFI_NETWORK_LIST_RESPONSE, USER_LIST_REQUEST, USER_LIST_RESPONSE, FIRMWARE_UPDATE_REQUEST, FIRMWARE_UPDATE_RESPONSE };
  }
  
  MessageType(int paramInt1) {
    this.value = paramInt1;
  }
  
  public static MessageType fromValue(byte paramByte) {
    for (MessageType messageType : values()) {
      if (messageType.value == paramByte)
        return messageType; 
    } 
    return null;
  }
  
  public byte getValue() {
    return (byte)this.value;
  }
}


/* Location:              C:\Users\rafal\Downloads\Mobius_jar.jar!\pl\com\mobilelabs\mobilus\model\communication\MessageType.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */